name: 'my_anime_pipeline'
version: '1.0.0'
config-version: 2

profile: 'my_anime_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  my_anime_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table